// Date: 25/09/2013 16:22:36
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelWalkWay extends ModelBase
{
  //fields
    ModelRenderer Railing3;
    ModelRenderer Railing4;
    ModelRenderer Railing8;
    ModelRenderer Railing10;
    ModelRenderer Railing2;
    ModelRenderer Railing9;
    ModelRenderer Railing1;
    ModelRenderer Railing6;
    ModelRenderer Railing7;
    ModelRenderer Railing5;
    ModelRenderer PlatformSideSingle;
    ModelRenderer PlatformSideDual;
  
  public ModelWalkWay()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Railing3 = new ModelRenderer(this, 34, 0);
      Railing3.addBox(-1F, -6F, 0F, 1, 12, 1);
      Railing3.setRotationPoint(0F, 16F, 7F);
      Railing3.setTextureSize(64, 32);
      Railing3.mirror = true;
      setRotation(Railing3, 0F, 0F, 1.570796F);
      Railing4 = new ModelRenderer(this, 34, 0);
      Railing4.addBox(0F, 0F, 0F, 1, 2, 1);
      Railing4.setRotationPoint(6F, 16F, 7F);
      Railing4.setTextureSize(64, 32);
      Railing4.mirror = true;
      setRotation(Railing4, 0F, 0F, -2.356194F);
      Railing8 = new ModelRenderer(this, 34, 0);
      Railing8.addBox(0F, -6F, 0F, 1, 12, 1);
      Railing8.setRotationPoint(0F, 10.17157F, 7F);
      Railing8.setTextureSize(64, 32);
      Railing8.mirror = true;
      setRotation(Railing8, 0F, 0F, 1.570796F);
      Railing10 = new ModelRenderer(this, 34, 0);
      Railing10.addBox(0F, -3F, 0F, 1, 3, 1);
      Railing10.setRotationPoint(6.414214F, 14.58579F, 7F);
      Railing10.setTextureSize(64, 32);
      Railing10.mirror = true;
      setRotation(Railing10, 0F, 0F, 0F);
      Railing2 = new ModelRenderer(this, 38, 0);
      Railing2.addBox(0F, 0F, 0F, 1, 8, 1);
      Railing2.setRotationPoint(4F, 16F, 7F);
      Railing2.setTextureSize(64, 32);
      Railing2.mirror = true;
      setRotation(Railing2, 0F, 0F, 0F);
      Railing9 = new ModelRenderer(this, 34, 0);
      Railing9.addBox(0F, 0F, 0F, 1, 2, 1);
      Railing9.setRotationPoint(6F, 10.17157F, 8F);
      Railing9.setTextureSize(64, 32);
      Railing9.mirror = true;
      setRotation(Railing9, 0F, 3.141593F, 0.7853982F);
      Railing1 = new ModelRenderer(this, 38, 0);
      Railing1.addBox(0F, 0F, 0F, 1, 8, 1);
      Railing1.setRotationPoint(-5F, 16F, 7F);
      Railing1.setTextureSize(64, 32);
      Railing1.mirror = true;
      setRotation(Railing1, 0F, 0F, 0F);
      Railing6 = new ModelRenderer(this, 34, 0);
      Railing6.addBox(0F, -3F, 0F, 1, 3, 1);
      Railing6.setRotationPoint(-7.414214F, 14.58579F, 7F);
      Railing6.setTextureSize(64, 32);
      Railing6.mirror = true;
      setRotation(Railing6, 0F, 0F, 0F);
      Railing7 = new ModelRenderer(this, 34, 0);
      Railing7.addBox(0F, 0F, 0F, 1, 2, 1);
      Railing7.setRotationPoint(-6F, 10.17157F, 7F);
      Railing7.setTextureSize(64, 32);
      Railing7.mirror = true;
      setRotation(Railing7, 0F, 0F, 0.7853982F);
      Railing5 = new ModelRenderer(this, 34, 0);
      Railing5.addBox(0F, 0F, 0F, 1, 2, 1);
      Railing5.setRotationPoint(-6F, 16F, 8F);
      Railing5.setTextureSize(64, 32);
      Railing5.mirror = true;
      setRotation(Railing5, 0F, 3.141593F, -2.356194F);
      PlatformSideSingle = new ModelRenderer(this, 0, 0);
      PlatformSideSingle.addBox(-8F, -7F, 0F, 16, 15, 1);
      PlatformSideSingle.setRotationPoint(0F, 24F, 0F);
      PlatformSideSingle.setTextureSize(64, 32);
      PlatformSideSingle.mirror = true;
      setRotation(PlatformSideSingle, 1.570796F, 3.141593F, 0F);
      PlatformSideDual = new ModelRenderer(this, 0, 16);
      PlatformSideDual.addBox(-8F, -7F, 0F, 16, 13, 1);
      PlatformSideDual.setRotationPoint(0F, 24F, 0F);
      PlatformSideDual.setTextureSize(64, 32);
      PlatformSideDual.mirror = true;
      setRotation(PlatformSideDual, 1.570796F, 3.141593F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Railing3.render(f5);
    Railing4.render(f5);
    Railing8.render(f5);
    Railing10.render(f5);
    Railing2.render(f5);
    Railing9.render(f5);
    Railing1.render(f5);
    Railing6.render(f5);
    Railing7.render(f5);
    Railing5.render(f5);
    PlatformSideSingle.render(f5);
    PlatformSideDual.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
