// Date: 09-Sep-13 4:54:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelNew extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer Bottom;
    ModelRenderer bottomright;
    ModelRenderer top;
    ModelRenderer extratopleft;
    ModelRenderer extratopright;
    ModelRenderer extrqtop;
    ModelRenderer bottomleft;
  
  public ModelNew()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(-8F, 0F, 2F, 16, 16, 6);
      base.setRotationPoint(0F, 8F, 0F);
      base.setTextureSize(64, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      Bottom = new ModelRenderer(this, 44, 0);
      Bottom.addBox(-3F, 1F, 0F, 6, 12, 2);
      Bottom.setRotationPoint(0F, 11F, 0F);
      Bottom.setTextureSize(64, 32);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      bottomright = new ModelRenderer(this, 60, 0);
      bottomright.addBox(-4F, 1F, 1F, 1, 13, 1);
      bottomright.setRotationPoint(0F, 10F, 0F);
      bottomright.setTextureSize(64, 32);
      bottomright.mirror = true;
      setRotation(bottomright, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 22);
      top.addBox(-3F, 1F, 0F, 6, 1, 1);
      top.setRotationPoint(0F, 10F, 1F);
      top.setTextureSize(64, 32);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      extratopleft = new ModelRenderer(this, 0, 24);
      extratopleft.addBox(3F, 1F, 1F, 1, 3, 1);
      extratopleft.setRotationPoint(0F, 7F, 0F);
      extratopleft.setTextureSize(64, 32);
      extratopleft.mirror = true;
      setRotation(extratopleft, 0F, 0F, 0F);
      extratopright = new ModelRenderer(this, 0, 24);
      extratopright.addBox(-4F, 1F, 1F, 1, 3, 1);
      extratopright.setRotationPoint(0F, 7F, 0F);
      extratopright.setTextureSize(64, 32);
      extratopright.mirror = true;
      setRotation(extratopright, 0F, 0F, 0F);
      extrqtop = new ModelRenderer(this, 5, 26);
      extrqtop.addBox(-3F, 1F, 0F, 6, 4, 2);
      extrqtop.setRotationPoint(0F, 7F, 0F);
      extrqtop.setTextureSize(64, 32);
      extrqtop.mirror = true;
      setRotation(extrqtop, 0F, 0F, 0F);
      bottomleft = new ModelRenderer(this, 60, 0);
      bottomleft.addBox(3F, 1F, 1F, 1, 13, 1);
      bottomleft.setRotationPoint(0F, 10F, 0F);
      bottomleft.setTextureSize(64, 32);
      bottomleft.mirror = true;
      setRotation(bottomleft, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    base.render(f5);
    Bottom.render(f5);
    bottomright.render(f5);
    top.render(f5);
    extratopleft.render(f5);
    extratopright.render(f5);
    extrqtop.render(f5);
    bottomleft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
