// Date: 14/08/2013 22:13:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelTank extends ModelBase
{
  //fields
    ModelRenderer TankSingleTop;
    ModelRenderer Support2;
    ModelRenderer Support1;
    ModelRenderer ViewerSingle5b;
    ModelRenderer ViewerSingle1b;
    ModelRenderer ViewerSingle2b;
    ModelRenderer ViewerSingle3b;
    ModelRenderer ViewerSingle3;
    ModelRenderer ViewerSingle2;
    ModelRenderer ViewerSingle1;
    ModelRenderer ViewerSingle5;
    ModelRenderer TankSingleBottom;
    ModelRenderer ViewerSingle4b;
    ModelRenderer ViewerSingle4;
  
  public ModelTank()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      TankSingleTop = new ModelRenderer(this, 0, 4);
      TankSingleTop.addBox(0F, 0F, 0F, 14, 7, 14);
      TankSingleTop.setRotationPoint(7F, 16F, -7F);
      TankSingleTop.setTextureSize(64, 64);
      TankSingleTop.mirror = true;
      setRotation(TankSingleTop, 0F, 0F, 3.141593F);
      Support2 = new ModelRenderer(this, 0, 0);
      Support2.addBox(0F, 0F, 0F, 16, 2, 2);
      Support2.setRotationPoint(6F, 22F, 8F);
      Support2.setTextureSize(64, 64);
      Support2.mirror = true;
      setRotation(Support2, 0F, 1.570796F, 0F);
      Support1 = new ModelRenderer(this, 0, 0);
      Support1.addBox(0F, 0F, 0F, 16, 2, 2);
      Support1.setRotationPoint(-8F, 22F, 8F);
      Support1.setTextureSize(64, 64);
      Support1.mirror = true;
      setRotation(Support1, 0F, 1.570796F, 0F);
      ViewerSingle5b = new ModelRenderer(this, 0, 4);
      ViewerSingle5b.addBox(0F, 0F, 0F, 4, 1, 1);
      ViewerSingle5b.setRotationPoint(-2F, 9F, -8F);
      ViewerSingle5b.setTextureSize(64, 64);
      ViewerSingle5b.mirror = true;
      setRotation(ViewerSingle5b, 0F, 0F, 0F);
      ViewerSingle1b = new ModelRenderer(this, 42, 0);
      ViewerSingle1b.addBox(0F, 0F, 0F, 1, 14, 1);
      ViewerSingle1b.setRotationPoint(2F, 9F, -8F);
      ViewerSingle1b.setTextureSize(64, 64);
      ViewerSingle1b.mirror = true;
      setRotation(ViewerSingle1b, 0F, 0F, 0F);
      ViewerSingle2b = new ModelRenderer(this, 42, 0);
      ViewerSingle2b.addBox(0F, 0F, 0F, 1, 14, 1);
      ViewerSingle2b.setRotationPoint(-3F, 9F, -8F);
      ViewerSingle2b.setTextureSize(64, 64);
      ViewerSingle2b.mirror = true;
      setRotation(ViewerSingle2b, 0F, 0F, 0F);
      ViewerSingle3b = new ModelRenderer(this, 58, 34);
      ViewerSingle3b.addBox(0F, 0F, 0F, 4, 12, 1);
      ViewerSingle3b.setRotationPoint(-2F, 10F, -8F);
      ViewerSingle3b.setTextureSize(64, 64);
      ViewerSingle3b.mirror = true;
      setRotation(ViewerSingle3b, 0F, 0F, 0F);
      ViewerSingle3 = new ModelRenderer(this, 58, 34);
      ViewerSingle3.addBox(0F, 0F, 0F, 4, 12, 1);
      ViewerSingle3.setRotationPoint(2F, 10F, 8F);
      ViewerSingle3.setTextureSize(64, 64);
      ViewerSingle3.mirror = true;
      setRotation(ViewerSingle3, 0F, 3.141593F, 0F);
      ViewerSingle2 = new ModelRenderer(this, 42, 0);
      ViewerSingle2.addBox(0F, 0F, 0F, 1, 14, 1);
      ViewerSingle2.setRotationPoint(-3F, 9F, 7F);
      ViewerSingle2.setTextureSize(64, 64);
      ViewerSingle2.mirror = true;
      setRotation(ViewerSingle2, 0F, 0F, 0F);
      ViewerSingle1 = new ModelRenderer(this, 42, 0);
      ViewerSingle1.addBox(0F, 0F, 0F, 1, 14, 1);
      ViewerSingle1.setRotationPoint(2F, 9F, 7F);
      ViewerSingle1.setTextureSize(64, 64);
      ViewerSingle1.mirror = true;
      setRotation(ViewerSingle1, 0F, 0F, 0F);
      ViewerSingle5 = new ModelRenderer(this, 0, 4);
      ViewerSingle5.addBox(0F, 0F, 0F, 4, 1, 1);
      ViewerSingle5.setRotationPoint(-2F, 9F, 7F);
      ViewerSingle5.setTextureSize(64, 64);
      ViewerSingle5.mirror = true;
      setRotation(ViewerSingle5, 0F, 0F, 0F);
      TankSingleBottom = new ModelRenderer(this, 0, 4);
      TankSingleBottom.addBox(0F, 0F, 0F, 14, 7, 14);
      TankSingleBottom.setRotationPoint(-7F, 16F, -7F);
      TankSingleBottom.setTextureSize(64, 64);
      TankSingleBottom.mirror = true;
      setRotation(TankSingleBottom, 0F, 0F, 0F);
      ViewerSingle4b = new ModelRenderer(this, 0, 4);
      ViewerSingle4b.addBox(0F, 0F, 0F, 4, 1, 1);
      ViewerSingle4b.setRotationPoint(-2F, 22F, -8F);
      ViewerSingle4b.setTextureSize(64, 64);
      ViewerSingle4b.mirror = true;
      setRotation(ViewerSingle4b, 0F, 0F, 0F);
      ViewerSingle4 = new ModelRenderer(this, 0, 4);
      ViewerSingle4.addBox(0F, 0F, 0F, 4, 1, 1);
      ViewerSingle4.setRotationPoint(-2F, 22F, 7F);
      ViewerSingle4.setTextureSize(64, 64);
      ViewerSingle4.mirror = true;
      setRotation(ViewerSingle4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    TankSingleTop.render(f5);
    Support2.render(f5);
    Support1.render(f5);
    ViewerSingle5b.render(f5);
    ViewerSingle1b.render(f5);
    ViewerSingle2b.render(f5);
    ViewerSingle3b.render(f5);
    ViewerSingle3.render(f5);
    ViewerSingle2.render(f5);
    ViewerSingle1.render(f5);
    ViewerSingle5.render(f5);
    TankSingleBottom.render(f5);
    ViewerSingle4b.render(f5);
    ViewerSingle4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
