// Date: 11/09/2013 19:41:41
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelWire extends ModelBase
{
  //fields
    ModelRenderer Center;
    ModelRenderer Down;
    ModelRenderer Up;
    ModelRenderer South;
    ModelRenderer East;
    ModelRenderer West;
    ModelRenderer DownConnector;
    ModelRenderer EastConnector;
    ModelRenderer WestConnector;
    ModelRenderer SouthConnector;
    ModelRenderer UpConnector;
    ModelRenderer EastWest;
    ModelRenderer UpDown;
    ModelRenderer ValveRod12;
    ModelRenderer ValveRod5;
    ModelRenderer ValveRod6;
    ModelRenderer ValveRod7;
    ModelRenderer ValveRod8;
    ModelRenderer ValveRod9;
    ModelRenderer ValveRod10;
    ModelRenderer ValveRod11;
    ModelRenderer ValveRod1;
    ModelRenderer ValveRod2;
    ModelRenderer ValveRod3;
    ModelRenderer ValveRod4;
    ModelRenderer ValveAxle;
  
  public ModelWire()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Center = new ModelRenderer(this, 0, 0);
      Center.addBox(-3F, -3F, -3F, 6, 6, 6);
      Center.setRotationPoint(0F, 16F, 0F);
      Center.setTextureSize(32, 32);
      Center.mirror = true;
      setRotation(Center, 0F, 0F, 0F);
      Down = new ModelRenderer(this, 0, 17);
      Down.addBox(-2F, -8F, -2F, 4, 5, 4);
      Down.setRotationPoint(0F, 16F, 0F);
      Down.setTextureSize(32, 32);
      Down.mirror = true;
      setRotation(Down, 3.141593F, 0F, 0F);
      Up = new ModelRenderer(this, 0, 17);
      Up.addBox(-2F, -8F, -2F, 4, 5, 4);
      Up.setRotationPoint(0F, 16F, 0F);
      Up.setTextureSize(32, 32);
      Up.mirror = true;
      setRotation(Up, 0F, 0F, 0F);
      South = new ModelRenderer(this, 0, 17);
      South.addBox(-2F, -8F, -2F, 4, 5, 4);
      South.setRotationPoint(0F, 16F, 0F);
      South.setTextureSize(32, 32);
      South.mirror = true;
      setRotation(South, -1.570796F, 0F, 0F);
      East = new ModelRenderer(this, 0, 17);
      East.addBox(-2F, -8F, -2F, 4, 5, 4);
      East.setRotationPoint(0F, 16F, 0F);
      East.setTextureSize(32, 32);
      East.mirror = true;
      setRotation(East, 0F, 0F, 1.570796F);
      West = new ModelRenderer(this, 0, 17);
      West.addBox(-2F, -8F, -2F, 4, 5, 4);
      West.setRotationPoint(0F, 16F, 0F);
      West.setTextureSize(32, 32);
      West.mirror = true;
      setRotation(West, 0F, 0F, -1.570796F);
      DownConnector = new ModelRenderer(this, 0, 26);
      DownConnector.addBox(-2.5F, -8F, -2.5F, 5, 1, 5);
      DownConnector.setRotationPoint(0F, 16F, 0F);
      DownConnector.setTextureSize(32, 32);
      DownConnector.mirror = true;
      setRotation(DownConnector, 0F, 0F, 3.141593F);
      EastConnector = new ModelRenderer(this, 0, 26);
      EastConnector.addBox(-2.5F, -8F, -2.5F, 5, 1, 5);
      EastConnector.setRotationPoint(0F, 16F, 0F);
      EastConnector.setTextureSize(32, 32);
      EastConnector.mirror = true;
      setRotation(EastConnector, 0F, 0F, 1.570796F);
      WestConnector = new ModelRenderer(this, 0, 26);
      WestConnector.addBox(-2.5F, -8F, -2.5F, 5, 1, 5);
      WestConnector.setRotationPoint(0F, 16F, 0F);
      WestConnector.setTextureSize(32, 32);
      WestConnector.mirror = true;
      setRotation(WestConnector, 0F, 0F, -1.570796F);
      SouthConnector = new ModelRenderer(this, 0, 26);
      SouthConnector.addBox(-2.5F, -8F, -2.5F, 5, 1, 5);
      SouthConnector.setRotationPoint(0F, 16F, 0F);
      SouthConnector.setTextureSize(32, 32);
      SouthConnector.mirror = true;
      setRotation(SouthConnector, -1.570796F, 0F, 0F);
      UpConnector = new ModelRenderer(this, 0, 26);
      UpConnector.addBox(-2.5F, -8F, -2.5F, 5, 1, 5);
      UpConnector.setRotationPoint(0F, 16F, 0F);
      UpConnector.setTextureSize(32, 32);
      UpConnector.mirror = true;
      setRotation(UpConnector, 0F, 0F, 0F);
      EastWest = new ModelRenderer(this, 16, 12);
      EastWest.addBox(-2F, -8F, -2F, 4, 15, 4);
      EastWest.setRotationPoint(0F, 16F, 0F);
      EastWest.setTextureSize(32, 32);
      EastWest.mirror = true;
      setRotation(EastWest, 0F, 0F, 1.570796F);
      UpDown = new ModelRenderer(this, 16, 12);
      UpDown.addBox(-2F, -8F, -2F, 4, 15, 4);
      UpDown.setRotationPoint(0F, 16F, 0F);
      UpDown.setTextureSize(32, 32);
      UpDown.mirror = true;
      setRotation(UpDown, 0F, 0F, 0F);
      ValveRod12 = new ModelRenderer(this, 22, 0);
      ValveRod12.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod12.setRotationPoint(0F, 16F, -5F);
      ValveRod12.setTextureSize(32, 32);
      ValveRod12.mirror = true;
      setRotation(ValveRod12, 0F, 0F, -0.7853982F);
      ValveRod5 = new ModelRenderer(this, 22, 0);
      ValveRod5.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod5.setRotationPoint(0F, 16F, -5F);
      ValveRod5.setTextureSize(32, 32);
      ValveRod5.mirror = true;
      setRotation(ValveRod5, 0F, 0F, 0F);
      ValveRod6 = new ModelRenderer(this, 22, 0);
      ValveRod6.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod6.setRotationPoint(0F, 16F, -5F);
      ValveRod6.setTextureSize(32, 32);
      ValveRod6.mirror = true;
      setRotation(ValveRod6, 0F, 0F, 0.7853982F);
      ValveRod7 = new ModelRenderer(this, 22, 0);
      ValveRod7.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod7.setRotationPoint(0F, 16F, -5F);
      ValveRod7.setTextureSize(32, 32);
      ValveRod7.mirror = true;
      setRotation(ValveRod7, 0F, 0F, 1.570796F);
      ValveRod8 = new ModelRenderer(this, 22, 0);
      ValveRod8.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod8.setRotationPoint(0F, 16F, -5F);
      ValveRod8.setTextureSize(32, 32);
      ValveRod8.mirror = true;
      setRotation(ValveRod8, 0F, 0F, 2.356194F);
      ValveRod9 = new ModelRenderer(this, 22, 0);
      ValveRod9.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod9.setRotationPoint(0F, 16F, -5F);
      ValveRod9.setTextureSize(32, 32);
      ValveRod9.mirror = true;
      setRotation(ValveRod9, 0F, 0F, 3.141593F);
      ValveRod10 = new ModelRenderer(this, 22, 0);
      ValveRod10.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod10.setRotationPoint(0F, 16F, -5F);
      ValveRod10.setTextureSize(32, 32);
      ValveRod10.mirror = true;
      setRotation(ValveRod10, 0F, 0F, -2.356194F);
      ValveRod11 = new ModelRenderer(this, 22, 0);
      ValveRod11.addBox(-2F, -4.8285F, 0F, 4, 1, 1);
      ValveRod11.setRotationPoint(0F, 16F, -5F);
      ValveRod11.setTextureSize(32, 32);
      ValveRod11.mirror = true;
      setRotation(ValveRod11, 0F, 0F, -1.570796F);
      ValveRod1 = new ModelRenderer(this, 21, 0);
      ValveRod1.addBox(0F, -0.5F, 0F, 4, 1, 1);
      ValveRod1.setRotationPoint(0F, 16F, -5F);
      ValveRod1.setTextureSize(32, 32);
      ValveRod1.mirror = true;
      setRotation(ValveRod1, 0F, 0F, -1.570796F);
      ValveRod2 = new ModelRenderer(this, 21, 0);
      ValveRod2.addBox(0F, -0.5F, 0F, 4, 1, 1);
      ValveRod2.setRotationPoint(0F, 16F, -5F);
      ValveRod2.setTextureSize(32, 32);
      ValveRod2.mirror = true;
      setRotation(ValveRod2, 0F, 0F, 0F);
      ValveRod3 = new ModelRenderer(this, 21, 0);
      ValveRod3.addBox(0F, -0.5F, 0F, 4, 1, 1);
      ValveRod3.setRotationPoint(0F, 16F, -5F);
      ValveRod3.setTextureSize(32, 32);
      ValveRod3.mirror = true;
      setRotation(ValveRod3, 0F, 0F, 1.570796F);
      ValveRod4 = new ModelRenderer(this, 21, 0);
      ValveRod4.addBox(0F, -0.5F, 0F, 4, 1, 1);
      ValveRod4.setRotationPoint(0F, 16F, -5F);
      ValveRod4.setTextureSize(32, 32);
      ValveRod4.mirror = true;
      setRotation(ValveRod4, 0F, 0F, 3.141593F);
      ValveAxle = new ModelRenderer(this, 24, 6);
      ValveAxle.addBox(-1F, 0.3333333F, -1F, 2, 4, 2);
      ValveAxle.setRotationPoint(0F, 16F, -6F);
      ValveAxle.setTextureSize(32, 32);
      ValveAxle.mirror = true;
      setRotation(ValveAxle, 1.570796F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Center.render(f5);
    Down.render(f5);
    Up.render(f5);
    South.render(f5);
    East.render(f5);
    West.render(f5);
    DownConnector.render(f5);
    EastConnector.render(f5);
    WestConnector.render(f5);
    SouthConnector.render(f5);
    UpConnector.render(f5);
    EastWest.render(f5);
    UpDown.render(f5);
    ValveRod12.render(f5);
    ValveRod5.render(f5);
    ValveRod6.render(f5);
    ValveRod7.render(f5);
    ValveRod8.render(f5);
    ValveRod9.render(f5);
    ValveRod10.render(f5);
    ValveRod11.render(f5);
    ValveRod1.render(f5);
    ValveRod2.render(f5);
    ValveRod3.render(f5);
    ValveRod4.render(f5);
    ValveAxle.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
