// Date: 12/09/2013 17:06:54
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelConveyor extends ModelBase
{
  //fields
    ModelRenderer ForwardCornerOut;
    ModelRenderer ForwardCornerCenter;
    ModelRenderer ForwardCornerIn2;
    ModelRenderer ForwardCornerIn1;
  
  public ModelConveyor()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      ForwardCornerOut = new ModelRenderer(this, 46, 0);
      ForwardCornerOut.addBox(-4F, 0F, 0F, 8, 4, 1);
      ForwardCornerOut.setRotationPoint(0F, 24F, 4F);
      ForwardCornerOut.setTextureSize(64, 32);
      ForwardCornerOut.mirror = true;
      setRotation(ForwardCornerOut, 1.570796F, 0F, 0F);
      ForwardCornerCenter = new ModelRenderer(this, 46, 5);
      ForwardCornerCenter.addBox(-4F, 0F, 0F, 8, 8, 1);
      ForwardCornerCenter.setRotationPoint(0F, 24F, -4F);
      ForwardCornerCenter.setTextureSize(64, 32);
      ForwardCornerCenter.mirror = true;
      setRotation(ForwardCornerCenter, 1.570796F, 0F, 0F);
      ForwardCornerIn2 = new ModelRenderer(this, 0, 0);
      ForwardCornerIn2.addBox(-4F, 0F, 0F, 8, 4, 1);
      ForwardCornerIn2.setRotationPoint(8F, 24F, 0F);
      ForwardCornerIn2.setTextureSize(64, 32);
      ForwardCornerIn2.mirror = true;
      setRotation(ForwardCornerIn2, 1.570796F, -1.570796F, 0F);
      ForwardCornerIn1 = new ModelRenderer(this, 0, 0);
      ForwardCornerIn1.addBox(-4F, 0F, 0F, 8, 4, 1);
      ForwardCornerIn1.setRotationPoint(-8F, 24F, 0F);
      ForwardCornerIn1.setTextureSize(64, 32);
      ForwardCornerIn1.mirror = true;
      setRotation(ForwardCornerIn1, 1.570796F, 1.570796F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    ForwardCornerOut.render(f5);
    ForwardCornerCenter.render(f5);
    ForwardCornerIn2.render(f5);
    ForwardCornerIn1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
