// Date: 17/09/2013 21:31:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelConveyor extends ModelBase
{
  //fields
    ModelRenderer ForwardBottom;
    ModelRenderer Support9Front;
    ModelRenderer Forward;
    ModelRenderer ForwardBody;
    ModelRenderer Support6Front;
    ModelRenderer Shape10Front;
    ModelRenderer Support5Front;
    ModelRenderer Support15;
    ModelRenderer Support11Back;
    ModelRenderer Support3;
    ModelRenderer Support8Back;
    ModelRenderer Support7Back;
    ModelRenderer Support2;
    ModelRenderer Support1;
    ModelRenderer Support4;
    ModelRenderer Support12Back;
    ModelRenderer Support14;
    ModelRenderer Support13;
    ModelRenderer Support12;
  
  public ModelConveyor()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      ForwardBottom = new ModelRenderer(this, 0, 0);
      ForwardBottom.addBox(-4F, 0F, 0F, 8, 16, 1);
      ForwardBottom.setRotationPoint(0F, 19F, -8F);
      ForwardBottom.setTextureSize(64, 32);
      ForwardBottom.mirror = true;
      setRotation(ForwardBottom, 1.570796F, 0F, 0F);
      Support9Front = new ModelRenderer(this, 60, 26);
      Support9Front.addBox(0F, 0F, 0F, 1, 5, 1);
      Support9Front.setRotationPoint(2F, 24F, -8F);
      Support9Front.setTextureSize(64, 32);
      Support9Front.mirror = true;
      setRotation(Support9Front, 1.570796F, 0F, 0F);
      Forward = new ModelRenderer(this, 0, 0);
      Forward.addBox(-4F, 0F, 0F, 8, 16, 1);
      Forward.setRotationPoint(0F, 16F, -8F);
      Forward.setTextureSize(64, 32);
      Forward.mirror = true;
      setRotation(Forward, 1.570796F, 0F, 0F);
      ForwardBody = new ModelRenderer(this, 48, 14);
      ForwardBody.addBox(0F, 0F, 0F, 6, 16, 2);
      ForwardBody.setRotationPoint(-3F, 16F, 8F);
      ForwardBody.setTextureSize(64, 32);
      ForwardBody.mirror = true;
      setRotation(ForwardBody, -1.570796F, 0F, 0F);
      Support6Front = new ModelRenderer(this, 60, 18);
      Support6Front.addBox(0F, 0F, 0F, 1, 7, 1);
      Support6Front.setRotationPoint(3F, 23F, -8F);
      Support6Front.setTextureSize(64, 32);
      Support6Front.mirror = true;
      setRotation(Support6Front, -2.356194F, 3.141593F, 0F);
      Shape10Front = new ModelRenderer(this, 60, 26);
      Shape10Front.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape10Front.setRotationPoint(-3F, 24F, -8F);
      Shape10Front.setTextureSize(64, 32);
      Shape10Front.mirror = true;
      setRotation(Shape10Front, 1.570796F, 0F, 0F);
      Support5Front = new ModelRenderer(this, 60, 18);
      Support5Front.addBox(0F, 0F, 0F, 1, 7, 1);
      Support5Front.setRotationPoint(-2F, 23F, -8F);
      Support5Front.setTextureSize(64, 32);
      Support5Front.mirror = true;
      setRotation(Support5Front, -2.356194F, 3.141593F, 0F);
      Support15 = new ModelRenderer(this, 60, 26);
      Support15.addBox(0F, 0F, 0F, 1, 4, 1);
      Support15.setRotationPoint(2F, 23F, 2F);
      Support15.setTextureSize(64, 32);
      Support15.mirror = true;
      setRotation(Support15, -1.570796F, 0F, 0F);
      Support11Back = new ModelRenderer(this, 60, 26);
      Support11Back.addBox(0F, 0F, 0F, 1, 5, 1);
      Support11Back.setRotationPoint(-3F, 23F, 8F);
      Support11Back.setTextureSize(64, 32);
      Support11Back.mirror = true;
      setRotation(Support11Back, -1.570796F, 0F, 0F);
      Support3 = new ModelRenderer(this, 60, 18);
      Support3.addBox(0F, 0F, 0F, 1, 5, 1);
      Support3.setRotationPoint(-3F, 24F, 3F);
      Support3.setTextureSize(64, 32);
      Support3.mirror = true;
      setRotation(Support3, 3.141593F, 0F, 0F);
      Support8Back = new ModelRenderer(this, 60, 18);
      Support8Back.addBox(0F, 0F, 0F, 1, 7, 1);
      Support8Back.setRotationPoint(-3F, 23F, 8F);
      Support8Back.setTextureSize(64, 32);
      Support8Back.mirror = true;
      setRotation(Support8Back, -2.356194F, 0F, 0F);
      Support7Back = new ModelRenderer(this, 60, 18);
      Support7Back.addBox(0F, 0F, 0F, 1, 7, 1);
      Support7Back.setRotationPoint(2F, 23F, 8F);
      Support7Back.setTextureSize(64, 32);
      Support7Back.mirror = true;
      setRotation(Support7Back, -2.356194F, 0F, 0F);
      Support2 = new ModelRenderer(this, 60, 18);
      Support2.addBox(0F, 0F, 0F, 1, 5, 1);
      Support2.setRotationPoint(2F, 24F, 3F);
      Support2.setTextureSize(64, 32);
      Support2.mirror = true;
      setRotation(Support2, 3.141593F, 0F, 0F);
      Support1 = new ModelRenderer(this, 60, 18);
      Support1.addBox(0F, 0F, 0F, 1, 5, 1);
      Support1.setRotationPoint(2F, 24F, -2F);
      Support1.setTextureSize(64, 32);
      Support1.mirror = true;
      setRotation(Support1, 3.141593F, 0F, 0F);
      Support4 = new ModelRenderer(this, 60, 18);
      Support4.addBox(0F, 0F, 0F, 1, 5, 1);
      Support4.setRotationPoint(-3F, 24F, -2F);
      Support4.setTextureSize(64, 32);
      Support4.mirror = true;
      setRotation(Support4, 3.141593F, 0F, 0F);
      Support12Back = new ModelRenderer(this, 60, 26);
      Support12Back.addBox(0F, 0F, 0F, 1, 5, 1);
      Support12Back.setRotationPoint(2F, 23F, 8F);
      Support12Back.setTextureSize(64, 32);
      Support12Back.mirror = true;
      setRotation(Support12Back, -1.570796F, 0F, 0F);
      Support14 = new ModelRenderer(this, 60, 26);
      Support14.addBox(0F, 0F, 0F, 1, 4, 1);
      Support14.setRotationPoint(2F, 23F, -2F);
      Support14.setTextureSize(64, 32);
      Support14.mirror = true;
      setRotation(Support14, -1.570796F, 1.570796F, 0F);
      Support13 = new ModelRenderer(this, 60, 26);
      Support13.addBox(0F, 0F, 0F, 1, 4, 1);
      Support13.setRotationPoint(2F, 23F, 3F);
      Support13.setTextureSize(64, 32);
      Support13.mirror = true;
      setRotation(Support13, -1.570796F, 1.570796F, 0F);
      Support12 = new ModelRenderer(this, 60, 26);
      Support12.addBox(0F, 0F, 0F, 1, 4, 1);
      Support12.setRotationPoint(-3F, 23F, 2F);
      Support12.setTextureSize(64, 32);
      Support12.mirror = true;
      setRotation(Support12, -1.570796F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    ForwardBottom.render(f5);
    Support9Front.render(f5);
    Forward.render(f5);
    ForwardBody.render(f5);
    Support6Front.render(f5);
    Shape10Front.render(f5);
    Support5Front.render(f5);
    Support15.render(f5);
    Support11Back.render(f5);
    Support3.render(f5);
    Support8Back.render(f5);
    Support7Back.render(f5);
    Support2.render(f5);
    Support1.render(f5);
    Support4.render(f5);
    Support12Back.render(f5);
    Support14.render(f5);
    Support13.render(f5);
    Support12.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
