// Date: 12/09/2013 13:47:45
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelConveyor extends ModelBase
{
  //fields
    ModelRenderer InputLeftElev;
    ModelRenderer InputRight;
    ModelRenderer InputRightElev;
    ModelRenderer InputLeft;
    ModelRenderer Forward;
    ModelRenderer ConnectorTopTube2;
    ModelRenderer ConnectorTop;
    ModelRenderer ConnectorTopSide2;
    ModelRenderer ConnectorTopSide4;
    ModelRenderer ConnectorTopSide1;
    ModelRenderer ConnectorTopSide3;
  
  public ModelConveyor()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      InputLeftElev = new ModelRenderer(this, 0, 24);
      InputLeftElev.addBox(-4F, -3F, 0F, 8, 3, 1);
      InputLeftElev.setRotationPoint(6F, 24F, 0F);
      InputLeftElev.setTextureSize(64, 32);
      InputLeftElev.mirror = true;
      setRotation(InputLeftElev, 1.047198F, 1.570796F, 0F);
      InputRight = new ModelRenderer(this, 0, 21);
      InputRight.addBox(-4F, -8F, 0F, 8, 2, 1);
      InputRight.setRotationPoint(0F, 24F, 0F);
      InputRight.setTextureSize(64, 32);
      InputRight.mirror = true;
      setRotation(InputRight, 1.570796F, 1.570796F, 0F);
      InputRightElev = new ModelRenderer(this, 0, 17);
      InputRightElev.addBox(-4F, -3F, 0F, 8, 3, 1);
      InputRightElev.setRotationPoint(-6F, 24F, 0F);
      InputRightElev.setTextureSize(64, 32);
      InputRightElev.mirror = true;
      setRotation(InputRightElev, 1.047198F, -1.570796F, 0F);
      InputLeft = new ModelRenderer(this, 0, 28);
      InputLeft.addBox(-4F, -8F, 0F, 8, 2, 1);
      InputLeft.setRotationPoint(0F, 24F, 0F);
      InputLeft.setTextureSize(64, 32);
      InputLeft.mirror = true;
      setRotation(InputLeft, 1.570796F, -1.570796F, 0F);
      Forward = new ModelRenderer(this, 0, 0);
      Forward.addBox(-4F, 0F, 0F, 8, 16, 1);
      Forward.setRotationPoint(0F, 24F, -8F);
      Forward.setTextureSize(64, 32);
      Forward.mirror = true;
      setRotation(Forward, 1.570796F, 0F, 0F);
      ConnectorTopTube2 = new ModelRenderer(this, 18, 25);
      ConnectorTopTube2.addBox(-2F, 0F, -2F, 4, 3, 4);
      ConnectorTopTube2.setRotationPoint(0F, 8F, 0F);
      ConnectorTopTube2.setTextureSize(64, 32);
      ConnectorTopTube2.mirror = true;
      setRotation(ConnectorTopTube2, 0F, 0F, 0F);
      ConnectorTop = new ModelRenderer(this, 18, 3);
      ConnectorTop.addBox(-3F, -3F, -3F, 6, 6, 6);
      ConnectorTop.setRotationPoint(0F, 14F, 0F);
      ConnectorTop.setTextureSize(64, 32);
      ConnectorTop.mirror = true;
      setRotation(ConnectorTop, 0F, 0F, 0F);
      ConnectorTopSide2 = new ModelRenderer(this, 18, 15);
      ConnectorTopSide2.addBox(0F, 0F, 0F, 6, 4, 1);
      ConnectorTopSide2.setRotationPoint(-4F, 12F, 3F);
      ConnectorTopSide2.setTextureSize(64, 32);
      ConnectorTopSide2.mirror = true;
      setRotation(ConnectorTopSide2, 0F, 1.570796F, 0F);
      ConnectorTopSide4 = new ModelRenderer(this, 18, 20);
      ConnectorTopSide4.addBox(0F, 0F, 0F, 8, 4, 1);
      ConnectorTopSide4.setRotationPoint(-4F, 12F, -4F);
      ConnectorTopSide4.setTextureSize(64, 32);
      ConnectorTopSide4.mirror = true;
      setRotation(ConnectorTopSide4, 0F, 0F, 0F);
      ConnectorTopSide1 = new ModelRenderer(this, 18, 15);
      ConnectorTopSide1.addBox(0F, 0F, 0F, 6, 4, 1);
      ConnectorTopSide1.setRotationPoint(3F, 12F, 3F);
      ConnectorTopSide1.setTextureSize(64, 32);
      ConnectorTopSide1.mirror = true;
      setRotation(ConnectorTopSide1, 0F, 1.570796F, 0F);
      ConnectorTopSide3 = new ModelRenderer(this, 18, 20);
      ConnectorTopSide3.addBox(0F, 0F, 0F, 8, 4, 1);
      ConnectorTopSide3.setRotationPoint(-4F, 12F, 3F);
      ConnectorTopSide3.setTextureSize(64, 32);
      ConnectorTopSide3.mirror = true;
      setRotation(ConnectorTopSide3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    InputLeftElev.render(f5);
    InputRight.render(f5);
    InputRightElev.render(f5);
    InputLeft.render(f5);
    Forward.render(f5);
    ConnectorTopTube2.render(f5);
    ConnectorTop.render(f5);
    ConnectorTopSide2.render(f5);
    ConnectorTopSide4.render(f5);
    ConnectorTopSide1.render(f5);
    ConnectorTopSide3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
