// Date: 14/08/2013 22:13:46
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelTank extends ModelBase
{
  //fields
    ModelRenderer TankCenter;
    ModelRenderer ViewerCenter3b;
    ModelRenderer ViewerCenter2b;
    ModelRenderer ViewerCenter1b;
    ModelRenderer ViewerCenter3;
    ModelRenderer ViewerCenter2;
    ModelRenderer ViewerCenter1;
  
  public ModelTank()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      TankCenter = new ModelRenderer(this, 8, 34);
      TankCenter.addBox(0F, 0F, 0F, 14, 16, 14);
      TankCenter.setRotationPoint(-7F, 8F, -7F);
      TankCenter.setTextureSize(64, 64);
      TankCenter.mirror = true;
      setRotation(TankCenter, 0F, 0F, 0F);
      ViewerCenter3b = new ModelRenderer(this, -5, 34);
      ViewerCenter3b.addBox(0F, 0F, 0F, 4, 16, 1);
      ViewerCenter3b.setRotationPoint(2F, 8F, -7F);
      ViewerCenter3b.setTextureSize(64, 64);
      ViewerCenter3b.mirror = true;
      setRotation(ViewerCenter3b, 0F, 3.141593F, 0F);
      ViewerCenter2b = new ModelRenderer(this, 42, 0);
      ViewerCenter2b.addBox(0F, 0F, 0F, 1, 16, 1);
      ViewerCenter2b.setRotationPoint(-3F, 8F, -8F);
      ViewerCenter2b.setTextureSize(64, 64);
      ViewerCenter2b.mirror = true;
      setRotation(ViewerCenter2b, 0F, 0F, 0F);
      ViewerCenter1b = new ModelRenderer(this, 42, 0);
      ViewerCenter1b.addBox(0F, 0F, 0F, 1, 16, 1);
      ViewerCenter1b.setRotationPoint(2F, 8F, -8F);
      ViewerCenter1b.setTextureSize(64, 64);
      ViewerCenter1b.mirror = true;
      setRotation(ViewerCenter1b, 0F, 0F, 0F);
      ViewerCenter3 = new ModelRenderer(this, -5, 34);
      ViewerCenter3.addBox(0F, 0F, 0F, 4, 16, 1);
      ViewerCenter3.setRotationPoint(-2F, 8F, 7F);
      ViewerCenter3.setTextureSize(64, 64);
      ViewerCenter3.mirror = true;
      setRotation(ViewerCenter3, 0F, 0F, 0F);
      ViewerCenter2 = new ModelRenderer(this, 42, 0);
      ViewerCenter2.addBox(0F, 0F, 0F, 1, 16, 1);
      ViewerCenter2.setRotationPoint(-3F, 8F, 7F);
      ViewerCenter2.setTextureSize(64, 64);
      ViewerCenter2.mirror = true;
      setRotation(ViewerCenter2, 0F, 0F, 0F);
      ViewerCenter1 = new ModelRenderer(this, 42, 0);
      ViewerCenter1.addBox(0F, 0F, 0F, 1, 16, 1);
      ViewerCenter1.setRotationPoint(2F, 8F, 7F);
      ViewerCenter1.setTextureSize(64, 64);
      ViewerCenter1.mirror = true;
      setRotation(ViewerCenter1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    TankCenter.render(f5);
    ViewerCenter3b.render(f5);
    ViewerCenter2b.render(f5);
    ViewerCenter1b.render(f5);
    ViewerCenter3.render(f5);
    ViewerCenter2.render(f5);
    ViewerCenter1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
