// Date: 14/08/2013 22:13:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelTank extends ModelBase
{
  //fields
    ModelRenderer TankTop;
    ModelRenderer ViewerTop4b;
    ModelRenderer ViewerTop1b;
    ModelRenderer ViewerTop2b;
    ModelRenderer ViewerTop3b;
    ModelRenderer ViewerTop3;
    ModelRenderer ViewerTop2;
    ModelRenderer ViewerTop1;
    ModelRenderer ViewerTop4;
  
  public ModelTank()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      TankTop = new ModelRenderer(this, 0, 4);
      TankTop.addBox(0F, 0F, 0F, 14, 15, 14);
      TankTop.setRotationPoint(7F, 24F, -7F);
      TankTop.setTextureSize(64, 64);
      TankTop.mirror = true;
      setRotation(TankTop, 0F, 0F, 3.141593F);
      ViewerTop4b = new ModelRenderer(this, 0, 4);
      ViewerTop4b.addBox(0F, 0F, 0F, 4, 1, 1);
      ViewerTop4b.setRotationPoint(-2F, 9F, -8F);
      ViewerTop4b.setTextureSize(64, 64);
      ViewerTop4b.mirror = true;
      setRotation(ViewerTop4b, 0F, 0F, 0F);
      ViewerTop1b = new ModelRenderer(this, 42, 0);
      ViewerTop1b.addBox(0F, 0F, 0F, 1, 15, 1);
      ViewerTop1b.setRotationPoint(2F, 9F, -8F);
      ViewerTop1b.setTextureSize(64, 64);
      ViewerTop1b.mirror = true;
      setRotation(ViewerTop1b, 0F, 0F, 0F);
      ViewerTop2b = new ModelRenderer(this, 42, 0);
      ViewerTop2b.addBox(0F, 0F, 0F, 1, 15, 1);
      ViewerTop2b.setRotationPoint(-3F, 9F, -8F);
      ViewerTop2b.setTextureSize(64, 64);
      ViewerTop2b.mirror = true;
      setRotation(ViewerTop2b, 0F, 0F, 0F);
      ViewerTop3b = new ModelRenderer(this, 58, 0);
      ViewerTop3b.addBox(0F, 0F, 0F, 4, 14, 1);
      ViewerTop3b.setRotationPoint(-2F, 10F, -8F);
      ViewerTop3b.setTextureSize(64, 64);
      ViewerTop3b.mirror = true;
      setRotation(ViewerTop3b, 0F, 0F, 0F);
      ViewerTop3 = new ModelRenderer(this, 58, 0);
      ViewerTop3.addBox(0F, 0F, 0F, 4, 14, 1);
      ViewerTop3.setRotationPoint(2F, 10F, 8F);
      ViewerTop3.setTextureSize(64, 64);
      ViewerTop3.mirror = true;
      setRotation(ViewerTop3, 0F, 3.141593F, 0F);
      ViewerTop2 = new ModelRenderer(this, 42, 0);
      ViewerTop2.addBox(0F, 0F, 0F, 1, 15, 1);
      ViewerTop2.setRotationPoint(-3F, 9F, 7F);
      ViewerTop2.setTextureSize(64, 64);
      ViewerTop2.mirror = true;
      setRotation(ViewerTop2, 0F, 0F, 0F);
      ViewerTop1 = new ModelRenderer(this, 42, 0);
      ViewerTop1.addBox(0F, 0F, 0F, 1, 15, 1);
      ViewerTop1.setRotationPoint(2F, 9F, 7F);
      ViewerTop1.setTextureSize(64, 64);
      ViewerTop1.mirror = true;
      setRotation(ViewerTop1, 0F, 0F, 0F);
      ViewerTop4 = new ModelRenderer(this, 0, 4);
      ViewerTop4.addBox(0F, 0F, 0F, 4, 1, 1);
      ViewerTop4.setRotationPoint(-2F, 9F, 7F);
      ViewerTop4.setTextureSize(64, 64);
      ViewerTop4.mirror = true;
      setRotation(ViewerTop4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    TankTop.render(f5);
    ViewerTop4b.render(f5);
    ViewerTop1b.render(f5);
    ViewerTop2b.render(f5);
    ViewerTop3b.render(f5);
    ViewerTop3.render(f5);
    ViewerTop2.render(f5);
    ViewerTop1.render(f5);
    ViewerTop4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
