package ip.industrialProcessing.microBlock.extend.connections;

import ip.industrialProcessing.microBlock.extend.connectingSides.IMicroBlockInterconnection;
import ip.industrialProcessing.microBlock.extend.externalConnections.IMicroBlockExternalConnection;

public interface IMicroBlockConnection extends IMicroBlockExternalConnection,IMicroBlockInterconnection{

}
