package mod.industrialProcessing.blockContainer.microblock;

import mod.industrialProcessing.blockContainer.microblock.extend.connectionCorners.TileEntityMicroBlockConnectionCorners;

public class MicroBlockTileEntity extends TileEntityMicroBlockConnectionCorners{

}
